config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/races/:id', to: 'races#show', as: 'race_show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circuit.rb
class Circuit < ActiveRecord::Base
  include ActiveModel::Model
  has_many :races

  self.primary_key = 'circuit_id'
end

app/models/constructor.rb
class Constructor < ActiveRecord::Base
  include ActiveModel::Model
  has_many :results

  self.primary_key = 'constructor_id'
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  include ActiveModel::Model
  has_many :results

  self.primary_key = 'driver_id'

  def name
    "#{forename} #{surname}"
  end

end

app/models/race.rb
class Race < ActiveRecord::Base
  include ActiveModel::Model
  belongs_to :circuit
  has_many :results

  self.primary_key = 'race_id'
  
  def winner
    results.find_by_position(1)
  end

  def finished
    results.where("status_id in (1, 11, 12, 13, 14, 15, 16, 17, 18, 19)").count
  end
end

app/models/result.rb
class Result < ActiveRecord::Base
  include ActiveModel::Model
  belongs_to :race
  belongs_to :driver
  belongs_to :constructor

  self.primary_key = 'result_id'

  def to_s
    "#{driver.name} | #{constructor.name} | #{position} | #{points} | #{fastest_lap_time}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
    def show
        @race = Race.find(params[:id])
    end
  end
  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>F1Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/races/show.html.erb
<h1><%= @race.name %> Results</h1>

<table>
<tr><th>Position</th><th>Driver</th><th>Constructor</th><th>Points</th><th>Laps</th><th>Grid</th><th>Change</th></tr>
<% @race.results.sort_by(&:position_order).each do |r| %>
    <tr>
        <td><%= r.position_order %></td>
        <td><%= r.driver.name %></td>
        <td><%= r.constructor.name %></td>
        <td><%= r.points.to_i %></td>
        <td><%= r.laps %></td>
        <td><%= r.grid %></td>
        <td><%= r.grid - r.position_order %></td>
    </tr>
<% end %>

app/views/welcome/index.html.erb
<h1>F1 Stats</h1>

<h2>2018 Results</h2>
<table>
    <tr><th>Race</th><th>Winner</th><th>Constructor</th><th># Finished</th></tr>
<% Race.where(year: 2018).each do |r| %>
        <tr>
        <td><%= link_to r.name, race_show_path(r) %></td>
        <td><%= r.winner.driver.name %></td>
        <td><%= r.winner.constructor.name %></td>
        <td><%= r.finished %></td>
        </tr>
<% end %>
</table>